version: '3.4'

services:
  orangecrush:
    image: orangecrush
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 443:443
